### ISSUE TITLE
Please Add to README.md the VDR wirbelscan Plugin.

### ISSUE THREAD

**Issue by wirbel-at-vdr-portal** [urfin78/w_scan_cpp-container#2]
You distribute as part of your binary package the VDR wirbelscan Plugin.

Please add it therefore to the README.md, as it
- is a separate package
- it has its own source code
- it has its own separate webpage
- it has its own license, which is not yet given here - even if its also GPLv2
- this binary package cannot be build without it.

thanks.

**Comment by urfin78** [comment]
Hi,

sorry that i forgot that, will fix it in a moment. I assumed it's a part auf w_scan itself. 

I hope that the whole container package is ok with you, as it's your code.
The main purpose was to build the 386 version for myself, so that I didn't have to do it on my low end machine ;-)

Thomas

**Comment by wirbel-at-vdr-portal** [comment]
Hi Thomas,

>> sorry that i forgot that, will fix it in a moment. I assumed it's a part auf w_scan itself.
>>
>> I hope that the whole container package is ok with you, as it's your code.
>>The main purpose was to build the 386 version for myself, so that I didn't have to do it on my low end machine ;-)


Everything ok now, thanks!

To distribute packages may help others,
no problem with that. :)

cheers,
Winfried
