### ISSUE TITLE
satip address

### ISSUE THREAD

**Issue by ncurado** [urfin78/w_scan_cpp-container#6]
Is there a way to specify the satip address?

**Comment by urfin78** [comment]
If w_scan_cpp supports this via an command line parameter, it should also be possible here, you can add all parameters like
`docker run ghcr.io/urfin78/w_scan_cpp:latest --help`

The help page of w_scan_cpp mentions 

>        -t, --satip
>              use SAT>IP tuner via VDR Satip Plugin
>              see https://www.satip.info

So something like

`docker run --device /dev/dvb/adapter0 ghcr.io/urfin78/w_scan_cpp:latest -s S19E2 --satip`

should work. But I don't have any satip hardware here, so I can't test it.
